version: '2.2'
services:
  db:
    image: bitnami/postgresql:12
    environment:
      POSTGRES_DB: box
      POSTGRESQL_PASSWORD: postgres
      BITNAMI_DEBUG: "true"
  db2:
    image: bitnami/postgresql:12
    environment:
      POSTGRES_DB: box
      POSTGRESQL_PASSWORD: postgres
      BITNAMI_DEBUG: "true"
  queue:
    image: perfumerlabs/queue:v1.3.0
    environment:
      QUEUE_WORKERS: "{\"box\":1}"
  box:
    image: git.perfumerlabs.com:5050/atameken/esb
    environment:
      BOX_ADMIN_USER: 1
      BOX_ADMIN_SECRET: 1
      BOX_INSTANCES: "http://box2"
      BOX_IS_SYSTEM: "true"
      PG_HOST: db
      PG_REAL_HOST: db
      PG_PORT: 5432
      PG_DATABASE: box
      PG_USER: postgres
      PG_PASSWORD: postgres
      TEST: "true"
    depends_on:
      db:
        condition: service_started
  box2:
    image: git.perfumerlabs.com:5050/atameken/esb
    environment:
      BOX_ADMIN_USER: 1
      BOX_ADMIN_SECRET: 1
      BOX_INSTANCES: "http://box"
      BOX_IS_SYSTEM: "true"
      PG_HOST: db2
      PG_REAL_HOST: db2
      PG_PORT: 5432
      PG_DATABASE: box
      PG_USER: postgres
      PG_PASSWORD: postgres
      TEST: "true"
    depends_on:
      db:
        condition: service_started